### ISSUE TITLE
AWS Cloud Infrastructure

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-jlrzarcor#2]
- [x] Crear la insfraestructura en AWS. Imagen a utilizar **opt2-aws-educate-17-03-2021**, en la región de Virginia.
- [x] Abrir los puertos de entrada de Jupyter_Lab para que el equipo pueda interactuar desde la nube.
- [x] Crear directorio de AWS y adjuntar screenshots, los cuáles deben mostrar:
 * Nombres, clave única o identificador del equipo.
 * Lista de experimentos ejecutados en kubeflow.
 * Algunos de los resultados del pipeline.
- [x]  Mantenimiento (cerrar bullet al concluir proyecto).

**Comment by jlrzarcor** [comment]
@all, favor de compartime su IP para la infraestructura.

Existe una forma muy rápida para validar el IP con la siguiente instrucción en cualquier browser:
**http://checkip.amazonaws.com/**

**Comment by Carlosrlpzi** [comment]
@jlrzarcor aquí dejo mi IP: 189.217.81.97/32

Gracias.
