### ISSUE TITLE
Services Deployment (minikube, kale y kubeflow)

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-jlrzarcor#3]
- [x] Levantar los servicios: minikube, kale y kubeflow.
- [x] Realizar lanzamientos con diferentes valores de parámetros del paquete desarrollado (problema de optimización convexa)
 * Cambiar puntos iniciales, cambiar criterios de paro, elegir nuevos ejemplos para experimentar.
 * Detectar con qué valores no funciona el programa
- [x] Reportar errores a _Programming Team_ para reimplemente el paquete.

**Referencias:**
Ver [video](https://www.youtube.com/watch?v=xL91E3FBgAg), muestra un ejemplo de _set-up_. Utilizar la guía [6.Minikube-y-AWS](https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/wiki/6.Minikube-y-AWS)

**Comment by jlrzarcor** [comment]
**Sprint Closing Session:**

@Carlosrlpzi En el commit anterior se integraron los notebooks de los tres experimentos para _Traveling Salesman Problem_ via _Hill Climbing_

**Notas Finales**: Tal como lo comentamos (dado que no se había podido subir previamente los notebooks), se obvervó que los tiempos de ejecución para 9 ciudades eran aceptables bajo distintos parámetros de punto inicial y tolerancia. No obstantes, para 10 y 11 ciudades, los tiempos no son aceptables (crecen desprorcionalmente en  comparación con los paquetes revisados previamente y con distintos criterios y tolerancias). De acuerdo a la corrección en el algoritmo que detectaste y realizaste, la cual mejora sustancialmente el tiempo de ejecución:

* Integrarla a nuestro paquete #4 .

**Comment by Carlosrlpzi** [comment]
Muy bien @jlrzarcor, acabo de añadir las correciones del nuevo paquete, este fue probado con 120  ciudades en un tiempo de ejecución bastante razonable de menos de un minuto. Esto nos ayudara en la implemetación en paralelo.
