### ISSUE TITLE
Dockering

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-jlrzarcor#7]
- [x] Integrar el código de programación del método numérico en un paquete en Python para que sea instalado a través de pip install y luego import .
- [x] Crear Dockerfile y colocarlo en este repo.
- [x] Construir imagen de docker que instale todo el software necesario para que funcione el paquete (con _Kale_ y sin _Kale_). Nombrar a esta imágen de forma distinta a la realizada anteriormente.
- [x] Actualizar el contenedor de docker mediante github actions.
- [x] Instalar en el contenedor el paquete trabajado por el equipo de programación.
- [x] Reflejar automáticamente con _github actions_ en la imágen los cambios de implementación generados durante el proceso de "Experimentación".

> * **Nota**: esta imágen debe construirse y alojarse (Build & Push) automáticamente en dockerhub con un lanzamiento de un workflow de github vía github actions. De esta forma, cualquier commit que modifique el Dockerfile debe lanzar un worfklow de github que dispare un build & push al dockerhub de manera automática.

**Comment by Carlosrlpzi** [comment]
Oye @Lobolc no esta agregada la linea de instalar requirements.txt, por favor agregala al Dockerfile.

**Comment by jlrzarcor** [comment]
@Lobolc 

Mike, porfa ayúdame a meter todas las dependencias re queridas en el Dockerfile, no individualmente

![image](https://user-images.githubusercontent.com/51694352/116793876-112ae080-aa8f-11eb-95a4-5800b09b6cc5.png)

**Comment by jlrzarcor** [comment]
@Lobolc , en el Actions aparecen duplicados los deployemnt de _Docker_image_ y _Docker_image_build and push_ debido a que en el código tienen el mismo nombre (no están diferenciados los que son 0 que hacen referencia a los sin kale. Me ayudas a modificarlo porfa.
Tnx
