### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-2-primera-parte-jlrzarcor#9]
Elaborar el reporte en un _jupyter notebook_.

- [x] Crear un _jupyter notebook_ con nombre **reporte_equipo_05_parte_1_practica_2.ipynb**. Debe contener:
 * Descripción de datasets utilizados.
 * Ejecución del paquete para los ejemplos elegidos.
 * Integrar la identificación de  celdas con el panel de kale 
  * Validar que al clonar el repo y desplegar el notebook en una infraestructura de minikube y kubeflow, el despliegue del pipeline termina exitosamente.
  * Resultados del uso del uso del software (paquete desarrollado) en los datasets.
- [x] Durante la reunión, se debe levantar la infraestructura de minikube con kubeflow y lanzar el pipeline con kale. El notebook mencionado en el primer _bullet_ se mostarará durante la reunión.

**Comment by Carlosrlpzi** [comment]
De acuerdo con cerrar el issue
